# Generated by Django 5.1.3 on 2024-11-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0003_alter_respuestaformulario_informacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaformulario',
            name='informacion',
            field=models.CharField(max_length=2),
        ),
    ]
